config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

get 'admin', to: 'admin#index'
get 'admin/movie', to: 'admin#movie'
get 'admin/show', to: 'admin#show'
get 'admin/theater', to: 'admin#theater'
get 'reserve', to: 'reserve#index'
get 'reserve/show/:id', to: 'reserve#show', as: 'buy'

post 'new/movie', to: 'movie#create'
post 'new/show', to: 'show#create'
post 'new/theater', to: 'theater#create'
post 'new/reserve', to: 'reserve#create'

scope '/admin' do
   resources :movie, :show, :theater
 end

end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/models/reserve.rb
class Reserve < ActiveRecord::Base
  belongs_to :show
  belongs_to :seat
end

app/models/seat.rb
class Seat < ActiveRecord::Base
  belongs_to :theater
end

app/models/show.rb
class Show < ActiveRecord::Base
  belongs_to :movie
  belongs_to :theater
end

app/models/theater.rb
class Theater < ActiveRecord::Base
	has_many :seats
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  	@moviesCount = Movie.count(:all)
	  @functionsCount = Show.count(:all)
	  @salasCount = Theater.count(:all)
	#@usersCount = User.count(:all)
	#@invoicesCount = Invoice.count(:all)
  end
  def movie
  	@movies = Movie.all
  end
  def theater
    @theaters = Theater.all
  end
  def show
    @shows = Show.all
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@shows = Show.all
  end
end

app/controllers/movie_controller.rb
class MovieController < ApplicationController
	def new
		@movie = Movie.new
	end

	def create	
		@movie = Movie.new
		movie_param = params[:movie]
		@movie.title = movie_param['title']
		@movie.genero = movie_param['genero']
		@movie.lenguage = movie_param['lenguage']
		@movie.duration = movie_param['duration']
		@movie.summary = movie_param['summary']
		@movie.classification = movie_param['classification']
		@movie.subtitle = movie_param['subtitle']
		@movie.release_date = movie_param['release_date']
		@movie.ext = movie_param['ext']
		if @movie.save
		  redirect_to admin_movie_path
		else
		  render 'new'
		end
	end
	def show
	    @movies = Movie.find(params[:id])
	end

	def edit
		@movie = Movie.find(params[:id])
	end



	def update
	  @movie = Movie.find(params[:id])
	 
	  @movie.update(movie_params)
	  redirect_to admin_movie_path
	end
	
	def destroy
	  @movie = Movie.find(params[:id])
	  @movie.destroy
	
	  redirect_to admin_movie_path
	end




	private
	  def movie_params
	    params.require(:movie).permit(:title, :genero, :lenguage, :subtitle, :duration, :release_date, :summary, :classification, :ext)
	  end
end

app/controllers/reserve_controller.rb
class ReserveController < ApplicationController
  helper_method :ocupado
  
  def index

  end
  def show
    @show_id = params[:id]
    @seats = seats @show_id

    #theater = show.theater
    #theater_id = theater.id
    #@seats = Seat.where(theater_id: theater_id)    
  end
  def create
    @reserve = Reserve.new
    reserve_param = params[:reserve]
    @movie.title = movie_param['title']
    if @reserve.save
      redirect_to admin_movie_path
    else
      render 'new'
    end
  end

  def ocupado(seat_id, show_id)
      reserve = Reserve.where(seat_id: seat_id).where(show_id: show_id)
      !reserve.empty?
    end

  def seats(id_show)
    @show = Show.find(params[:id]).theater.seats
  end

private
  def check_available(id_show)
    @show = Show.find(params[:id])
    @show.theater.quantity
  end
    def show_params
      params.require(:show).permit(:id)
    end
end

app/controllers/show_controller.rb
class ShowController < ApplicationController
	def new
		@show = Show.new
	end
	def create
		
		@show = Show.new
		show_param = params[:show]
		
		@show.date_show = show_param['date_show']
		@show.time_show = show_param['time_show']
		@show.movie_id = show_param['movie_id']
		@show.theater_id = show_param['theater_id']

		if @show.save
		  	redirect_to admin_show_path
		else
		  render 'new'
		end
		 
	end
	def show
	    @show = Show.find(params[:id])
	end

	def edit
		@show = Show.find(params[:id])
	end



	def update
	  @show = Show.find(params[:id])
	 
	  @show.update(show_params)
	  redirect_to admin_show_path
	end
	
	def destroy
	  @show = Show.find(params[:id])
	  @show.destroy
	
	  redirect_to admin_show_path
	end

	private
	  def show_params
	    params.require(:show).permit(:date_show, :time_show, :movie_id, :theater_id)
	  end
end

app/controllers/theater_controller.rb
class TheaterController < ApplicationController
	def new
		@theater = Theater.new
	end

	def create	
		@theater = Theater.new
		theater_param = params[:theater]
		@theater.name = theater_param['name']
		@theater.quantity = theater_param['quantity']
		if @theater.save
		  redirect_to admin_theater_path
		else
		  render 'new'
		end
	end
	def show
	    @theaters = Theater.find(params[:id])
	end

	def edit
		@theater = Theater.find(params[:id])
	end



	def update
	  @theater = Theater.find(params[:id])
	 
	  @theater.update(theater_params)
	  redirect_to admin_theater_path
	end
	
	def destroy
	  @theater = Theater.find(params[:id])
	  @theater.destroy
	
	  redirect_to admin_theater_path
	end




	private
	  def theater_params
	    params.require(:theater).permit(:name, :quantity)
	  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/function_helper.rb
module FunctionHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/reserve_helper.rb
module ReserveHelper
end

app/helpers/theater_helper.rb
module TheaterHelper
end

app/views/admin/index.html.erb
<div class="container">
  <div class="row boxs">
    <div class="col-md-12">
    <a href="<%= admin_movie_path %>" style="text-decoration:none">
      <div class="box">
        <p class="title_box">Peliculas</p>
        <div class="row">
          <div class="col-md-6">
            <span class="fa-film icon_box"></span> 
          </div>
          <div class="col-md-6">
             <p class="count_adm"><%= @moviesCount %></p>
          </div>
        </div>

      </div>
      </a>
      <a href="<%= admin_show_path %>" style="text-decoration:none">  
        <div class="box2">
          <p class="title_box">Funciones</p>
          <div class="row">
            <div class="col-md-6">
              <span class="fa-clock-o icon_box"></span> 
            </div>
            <div class="col-md-6">
              <p class="count_adm"><%= @functionsCount %></p>    
            </div>
          </div>
        </div>
      </a>
      <a href="<%= admin_theater_path %>" style="text-decoration:none">  
        <div class="box3">
          <p class="title_box">Salas</p>
          <div class="row">
            <div class="col-md-6">
              <span class="fa-clock-o icon_box"></span> 
            </div>
            <div class="col-md-6">
              <p class="count_adm"><%= @salasCount %></p>
            </div>
          </div>
        </div>
      </a>
      <div class="box4">
        <p class="title_box">Usuarios</p>
        <div class="row">
          <div class="col-md-6">
            <span class="fa-user icon_box"></span> 
          </div>
          <div class="col-md-6">
            <p class="count_adm">2</p>
          </div>
        </div>
      </div>
      <div class="box5">
        <p class="title_box">Factura</p>
        <div class="row">
          <div class="col-md-6">
            <span class="fa-usd icon_box"></span> 
          </div>
          <div class="col-md-6">
            <p class="count_adm">3</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/movie.html.erb
<div class="container">
  <div class="row color_movie">
    <div class="col-md-12">
    <div class="row movie_show">
      <div class="col-md-10">
          <h3 class="color_white">Peliculas</h3>
      </div>
      <div class="col-md-2">
        <button type="button" class="btn btn-default form_create">Nueva Pelicula</button>
      </div>
    </div>
      <div class="row">

        <div class="col-md-12">
          <div class="row">
            <div class="col-md-12 form_movie">
              <%= form_tag new_movie_path, method: :post, class: "form-inline" do %>
                  <%= label_tag :Titulo %>
                  <%= text_field :movie, :title, class: "form-control" %>
                  <%= label_tag :Genero %>
                  <%= text_field :movie, :genero, class: "form-control" %>
                 <%= label_tag :Lenguaje %>
                 <%= text_field :movie, :lenguage, class: "form-control" %>
                 <%= label_tag :Subtitulo %>
                 <%= text_field :movie, :subtitle, class: "form-control" %>
                 </br></br>
                 <%= label_tag :Duracion %>
                 <%= time_field :movie, :duration, class: "form-control" %>

                 <%= label_tag :Extreno %>
                 <%= date_field :movie, :release_date, class: "form-control" %>

                 <%= label_tag :Sinopsis %>
                 <%= text_area :movie, :summary, class: "form-control" %>
                 <%= label_tag :Clasificacion %>
                 <%= text_field :movie, :classification, class: "form-control" %>
                 </br>
                 <%= label_tag :Imagen %>
                 <%= text_field :movie, :ext, class: "form-control  " %>

                <p class="text-center">
                  <%= submit_tag "Enviar", class: "btn btn-primary" %>
                </p>
              <% end %>
            </div>
          </div>
          <div class="row">
          <div class="col-md-12">
          <table class="table table-striped table-hover table_styl">
                <tr>
                  <th>Titulo</th>
                  <th>Genero</th>
                  <th>Language</th>
                  <th>Subtitulos</th>
                  <th>Duration</th>
            <th>Release_date</th>
            <th>Summary</th>
            <th>Classificacion</th>
            <th>Imagen</th>
                  <th colspan="3">Aciones</th>
                </tr>
               
                <% @movies.each do |movie| %>
                  <tr>
                    <td><%= movie.title %></td>
                    <td><%= movie.genero %></td>
                    <td><%= movie.lenguage %></td>
                    <td><%= movie.subtitle %></td>
                    <td><%= movie.duration %></td>
                    <td><%= movie.release_date %></td>
                    <td><%= movie.summary %></td>
                    <td><%= movie.classification %></td>
                    <td><%= image_tag movie.ext, :class => "img_preview" %></td>
                    <td><%= link_to 'Show', movie_path(movie) %></td>
                    <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
                    <td><%= link_to 'Destroy', movie_path(movie),
                                  method: :delete,
                                  data: { confirm: 'Estas seguro que desea eliminar esta pelicula?' } %></td>         
                  </tr>
                <% end %>
          </table>
          </div>      
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(function(){
  $('.form_create').on('click', mostrarFormulario)
  function mostrarFormulario(){
    $('.form_movie').slideToggle()
  }
});
</script>

app/views/admin/show.html.erb
<div class="container">
  <div class="row color_movie">
    <div class="col-md-12">
    <div class="row movie_shows">
      <div class="col-md-10">
          <h3 class="color_white">Funciones</h3>
      </div>
      <div class="col-md-2">
        <button type="button" class="btn btn-default form_create">Nueva Funcion</button>
      </div>
    </div>
      <div class="row">

        <div class="col-md-12">
          <div class="row">
            <div class="col-md-12 form_movie">
              <%= form_tag new_show_path, method: :post, class: "form-inline" do %>
                  <%= label_tag :Fecha %>
                  <%= date_field :show, :date_show, class: "form-control" %>
                  <%= label_tag :Hora %>
                  <%= time_field :show, :time_show, class: "form-control" %>
                  <%= label_tag(:id_movie, "Pelicula:") %>
                  <%=collection_select(:show, :movie_id, Movie.order(:title), :id, :title) %>
                  <%= label_tag(:id_theater, "Sala:") %>
                  <%=collection_select(:show, :theater_id, Theater.order(:name), :id, :name) %>

                <p class="text-center">
                  <%= submit_tag "Enviar", class: "btn btn-success" %>
                </p>
              <% end %>
            </div>
          </div>
          <div class="row">
          <div class="col-md-12">
          <table class="table table-striped table-hover table_styl">
             <tr>
                <th>Fecha</th>
                <th>Hora</th>
                <th>Pelicula</th>
                <th>Sala</th>
                <th colspan="3">Aciones</th>
              </tr>
             
              <% @shows.each do |show| %>
              <% @movie_id = Movie.find(show.movie_id) %>
              <% @movie_title = @movie_id.title %>
              <% @theater_id = Theater.find(show.theater_id) %>
              <% @theater_name = @theater_id.name %>
                <tr>
                  <td><%= show.date_show %></td>
                  <td><%= show.time_show %></td>
                  <td><%= @movie_title %></td>
                  <td><%= @theater_name %></td>
                  <td><%= link_to 'Show', show_path(show) %></td>
                  <td><%= link_to 'Edit', edit_show_path(show) %></td>
                  <td><%= link_to 'Destroy', show_path(show),
                                method: :delete,
                                data: { confirm: 'Estas seguro que desea eliminar esta pelicula?' } %></td>         
                </tr>
              <% end %>
          </table>
          </div>      
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(function(){
  $('.form_create').on('click', mostrarFormulario)
  function mostrarFormulario(){
    $('.form_movie').slideToggle()
  }
});
</script>

app/views/admin/theater.html.erb
<div class="container">
  <div class="row color_movie">
    <div class="col-md-12">
    <div class="row theater_shows">
      <div class="col-md-10">
          <h3 class="color_white">Salas</h3>
      </div>
      <div class="col-md-2">
        <button type="button" class="btn btn-default form_create">Nueva Sala</button>
      </div>
    </div>
      <div class="row">

        <div class="col-md-12">
          <div class="row">
            <div class="col-md-12 form_movie">
              <%= form_tag new_theater_path, method: :post, class: "form-inline" do %>
                  <%= label_tag :Nombre %>
                  <%= text_field :theater, :name, class: "form-control" %>
                  <%= label_tag :Cantidad %>
                  <%= number_field :theater, :quantity, class: "form-control" %>
                <p class="text-center">
                  <%= submit_tag "Enviar", class: "btn btn-warning" %>
                </p>
              <% end %>
            </div>
          </div>
          <div class="row">
          <div class="col-md-12">
          <table class="table table-striped table-hover table_styl">
                <tr>
                  <th>Nombre</th>
                  <th>Cantidad</th>
                  <th colspan="3">Aciones</th>
                </tr>
               
                <% @theaters.each do |theater| %>
                  <tr>
                    <td><%= theater.name %></td>
                    <td><%= theater.quantity %></td>
                    <td><%= link_to 'Show', theater_path(theater) %></td>
                    <td><%= link_to 'Edit', edit_theater_path(theater) %></td>
                    <td><%= link_to 'Destroy', theater_path(theater),
                                  method: :delete,
                                  data: { confirm: 'Estas seguro que desea eliminar esta pelicula?' } %></td>         
                  </tr>
                <% end %>
          </table>
          </div>      
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(function(){
  $('.form_create').on('click', mostrarFormulario)
  function mostrarFormulario(){
    $('.form_movie').slideToggle()
  }
});
</script>

app/views/home/index.html.erb
<div class="container-fluid">
	<div class="header navbar-fixed-top" >
		<div class="slogan col-md-5">	
			<h1>IMAX Caracas</h1>
		</div>	
		<div class="col-md-6 logo">
			<%= image_tag 'movie_film.png' %>

		</div>
	</div>

	<% @shows.each do |show| %>
	<div class= "movie-box col-md-12 ">
	<div class="img-pelicula col-md-2">
		<img src="<%= show.movie.ext %>">
		</div>
		<div class="nombre col-md-2">
			<h1><%= show.movie.title %></h1>
			<h4><%= show.movie.genero %></h4>
			<h1><%= show.movie.subtitle%></h1>
			<h1><%= show.movie.classification%></h1>
		</div>
		<div class="sinpsis col-md-2">
			<p><%= show.movie.summary %></p>
		</div>
		<div class="seccion-compra col-md-4">
			<h1>Compra</h1>
			<a href="<%= buy_path(show) %>"><button type="button" class="btn btn-warning"><a href="<%= buy_path(show) %>">Comprar!!</button></a>

		</div>
	</div>
	<% end  %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackmax</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body class="body_admin">
</div><nav class="main-menu">  
<div>

 </div>

     
<ul>
 
<li>                                   
<a href="<%= admin_path %>">
<i class="fa fa-home fa-lg"></i>
<span class="nav-text">Home</span>
</a>
</li>   
  
<li>
<a href="<%= admin_movie_path %>">                              
<i class="fa fa-film fa-lg"></i>
<span class="nav-text">Películas</span>
</a>
</li>  

   
<li>                                 
<a href="http://startific.com">
<i class="fa fa-usd fa-lg"></i>
<span class="nav-text">Precio de Entradas</span>
</a>
</li>   
 


                             
                           
                     
                      
                       </span>
                       <span class="nav-text">
                       </span>
                       
                   </a>

</li>
                           

 
 
</li>
<li class="darkerlishadow">
<a href="<%= admin_show_path %>">
<i class="fa fa-clock-o fa-lg"></i>
<span class="nav-text">Funciones</span>
</a>
</li>
 
<li class="darkerli">
<a href="<%= admin_theater_path %>">
<i class="fa fa-desktop fa-lg"></i>
<span class="nav-text">Salas</span>
</a>
</li>
 
<li class="darkerli">
<a href="http://startific.com">
<i class="fa fa-plane fa-lg"></i>
<span class="nav-text">Travel</span>
</a>
</li>
 
<li class="darkerli">
<a href="http://startific.com">
<i class="fa fa-shopping-cart"></i>
<span class="nav-text">Shopping</span>
</a>
</li>
 
<li class="darkerli">
<a href="http://startific.com">
<i class="fa fa-microphone fa-lg"></i>
<span class="nav-text">Film & Music</span>
</a>
</li>

<li class="darkerli">
<a href="http://startific.com">
<i class="fa fa-flask fa-lg"></i>
<span class="nav-text">Web Tools</span>
</a>
</li>
 
<li class="darkerli">
<a href="http://startific.com">
<i class="fa fa-picture-o fa-lg"></i>
<span class="nav-text">Art & Design</span>
</a>
</li>

<li class="darkerli">
<a href="http://startific.com">
<i class="fa fa-align-left fa-lg"></i>
<span class="nav-text">Magazines
</span>
</a>
</li>
 
<li class="darkerli">
<a href="http://startific.com">
<i class="fa fa-gamepad fa-lg"></i>
<span class="nav-text">Games</span>
</a>
</li>
 
<li class="darkerli">
<a href="http://startific.com">
<i class="fa fa-glass fa-lg"></i>
<span class="nav-text">Life & Style
</span>
</a>
</li>
 
<li class="darkerlishadowdown">
<a href="http://startific.com">
<i class="fa fa-rocket fa-lg"></i>
<span class="nav-text">Fun</span>
</a>
</li>
</ul>  
</nav>


<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackMax - IMAX Caracas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movie/_form.html.erb
<h1>Editing article</h1>
 
<%= form_tag :movie, url: movie_path(@movie), method: :patch do |f| %>
 
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@movie.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @amovie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
   <p>
     <%= label_tag :Titulo %><br>
     <%= text_field :movie, :title %>
   </p>
  
   <p>
     <%= label_tag :Genero %><br>
     <%= text_field :movie, :genero %>
   </p>
  <p>
    <%= label_tag :Lenguaje %><br>
    <%= text_field :movie, :lenguage %>
  </p>
  <p>
    <%= label_tag :Subtitulo %><br>
    <%= text_field :movie, :subtitle %>
  </p>
  <p>
    <%= label_tag :Duracion %><br>
    <%= time_field :movie, :duration %>
  </p>
  <p>
    <%= label_tag :Extreno %><br>
    <%= date_field :movie, :release_date %>
  </p>
  <p>
    <%= label_tag :Sinopsis %><br>
    <%= text_area :movie, :summary %>
  </p>
  <p>
    <%= label_tag :Imagen %><br>
    <%= text_field :movie, :ext %>
  </p>
  <p>
    <%= label_tag :Clasificacion %><br>
    <%= text_field :movie, :classification%>
  </p>
  <p>
    <%= submit_tag "Enviar" %>
  </p>
 
<% end %>
 
<%= link_to 'Back', movie_path %>

app/views/movie/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back to Movies', admin_movie_path %>

app/views/movie/show.html.erb
<p>
	<strong>Titulo</strong>
<%= @movies.title %>
</p>
<p>
	<strong>Genero</strong>
<%= @movies.genero %>
</p>
<p>
	<strong>Lenguaje</strong>
<%= @movies.lenguage %>
</p>
<p>
	<strong>Subtitulos</strong>
<%= @movies.subtitle %>
</p>
<p>
	<strong>Duraccion</strong>
<%= @movies.duration %>
</p>
<p>
	<strong>Fecha de Estreno</strong>
<%= @movies.release_date %>
</p>
<p>
	<strong>Sinopsis</strong>
<%= @movies.summary %>
</p>
<p>
	<strong>Clasificacion</strong>
<%= @movies.classification %>
</p>
<p>
	<strong>Imagen</strong>
<%= @movies.ext %>
</p>

 

app/views/reserve/index.html.erb
<div>
  <% @seats.each do |seat| %>
      <p class="<%= seat.status %>"> Asiento</p>
  <% end %>
</div>

app/views/reserve/show.html.erb
<div class="container">
	<div class="row seats_row">
		<div class="col-md-6 col-md-offset-3">
    <div class="row">
      <div class="col-md-12 status">
        <strong class="avaible"> Disponible </strong> <strong class="choice"> Selecionado </strong> <strong class="not_avaible"> No Disponible </strong>
      </div>
    </div>
      <% @seats.each do |seat| %>
          <% if ocupado seat.id, @show_id %>
            <div id="<%= seat.id %>" class="seats O">
              
            </div>
            <% else %>
              <div id="<%= seat.id %>" class="seats D">
              
              </div>
          <% end %>
        <% end %>
    </div>
    <div class="col-md-3">
      <aside class="count_price">
        <div class="checked-place">            
        </div>
        <div class="checked-result">
            0
        </div>
      </aside>
    </div>
  </div>
</div>
<div>
  <%= form_tag new_movie_path, method: :put do %>
    <div id="form_submit"></div>
    <p class="text-center">
      <%= submit_tag "Enviar", class: "btn btn-primary" %>
    </p>
  <% end %>
</div>
        

app/views/show/_form.html.erb
<h1>Editing article</h1>
 
<%= form_tag :show, url: show_path(@show), method: :put do |f| %>
 
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@show.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @show.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <p>
    <%= label_tag(:show, "fecha:") %>
    <%= date_field(:show, :date_show) %>
  </p>
  <p>
    <%= label_tag(:show, "hora:") %>
    <%= time_field(:show, :time_show) %>
  </p>
  <p>
    <%= label_tag(:id_movie, "Pelicula:") %>
    <%=collection_select(:show, :movie_id, Movie.all, :id, :title) %>
  </p>
  <p>
    <%= label_tag(:id_sala, "Sala:") %>
    <%=collection_select(:show, :theater_id, Theater.all, :id, :name) %>
  </p>
 

  <p>
    <%= submit_tag "Enviar" %>
  </p>
 
<% end %>
 
<%= link_to 'Back', show_path %>

app/views/show/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 

app/views/show/show.html.erb
<p>
	<strong>Fecha</strong>
<%= @show.date_show %>
</p>
<p>
	<strong>Hora</strong>
<%= @show.time_show %>
</p>
<p>
	<strong>Pelicula</strong>
<%= @show.movie_id %>
</p>
<p>
	<strong>Sala</strong>
<%= @show.theater_id %>
</p>

app/views/theater/_form.html.erb
<h1>Editing article</h1>
 
<%= form_tag :theater, url: theater_path(@theater), method: :patch do |f| %>
 
  <% if @theater.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@theater.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @atheater.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
   <p>
     <%= label_tag :Nombre %><br>
     <%= text_field :theater, :name %>
   </p>
   <p>
   <%= label_tag :Cantidad %>
  <%= number_field :theater, :quantity%>
  </p>
   
  <p>
    <%= submit_tag "Enviar" %>
  </p>
 
<% end %>
 
<%= link_to 'Back', theater_path %>

app/views/theater/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back to Movies', admin_movie_path %>

app/views/theater/show.html.erb
<p>
	<strong>Titulo</strong>
<%= @theaters.name %>
</p>